### ISSUE TITLE
EPIC: PostgreSQL initial content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#112]
- [x] PostgreSQL overview #75 
- [x] PostgreSQL getting started #84 
- [x] PostgreSQL connecting article #93 
- [x] PostgreSQL migrating article #102
