### ISSUE TITLE
EPIC: Kafka initial content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#113]
- [x] Kafka overview #76 
- [x] Kafka getting started #85 
- [x] Kafka connecting article #94 
- [ ] Kafka migrating article #103

**Comment by lornajane** [comment]
I'll close the epic but the migration task would still be a nice-to-have
