### ISSUE TITLE
EPIC: MySQL initial content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#115]
- [x] MySQL overview #78 
- [x] MySQL getting started #87 
- [x] MySQL connecting article #96 
- [x] MySQL migrating article #105

**Comment by laysauchoa** [comment]
This Issue epic seems to be complete, so I am closing it.
