### ISSUE TITLE
EPIC: Redis initial content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#116]
- [x] Redis overview #79 
- [x] Redis getting started #88 
- [x] Redis connecting article #97 
- [x] Redis migrating article #106 
- [x] https://github.com/aiven/devportal/issues/432
- [x] https://github.com/aiven/devportal/issues/433
- [x] https://github.com/aiven/devportal/issues/435
- [x] https://github.com/aiven/devportal/issues/437

**Comment by laysauchoa** [comment]
Feel free to add to this list: https://github.com/aiven/devportal/issues/432

**Comment by laysauchoa** [comment]
I do not see any more article from redis to migrate.

**Comment by lornajane** [comment]
Do we need this one? https://help.aiven.io/en/articles/1110366-eval-and-load-script-commands

**Comment by laysauchoa** [comment]
no longer relevant as all the clients have it enabled by default so this article can be removed from the docs.

**Comment by lornajane** [comment]
Great! Could we add a note in the migration spreadsheet so we know why it hasn't bee migrated? Then I think it's just #97 that we need to work on before we close this epic!

**Comment by laysauchoa** [comment]
I think this initial epic can be closed, @lornajane 
what do you think?

**Comment by lornajane** [comment]
:tada:
