### ISSUE TITLE
EPIC: Cassandra initial content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#117]
- [x] Cassandra overview #80 
- [x] Cassandra getting started #89 
- [x] Cassandra connecting article #98 
- [ ] Cassandra migrating article #107

**Comment by lornajane** [comment]
migration phase complete
