### ISSUE TITLE
EPIC: OpenSearch initial content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#118]
Open PRs for all opensearch content with the `opensearch` branch as the base branch.

- [x] OpenSearch overview #81 
- [x] OpenSearch getting started #108 
- [x] OpenSearch connecting article #99 
- [x] OpenSearch migrating article #109
