### ISSUE TITLE
EPIC: InfluxDB initial content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#120]
- [ ] InfluxDB overview #83 
- [ ] InfluxDB getting started #92  
- [ ] InfluxDB connecting article #101 
- [ ] InfluxDB migrating article #111

**Comment by laysauchoa** [comment]
https://github.com/aiven/devportal/issues/788

**Comment by lornajane** [comment]
This is covered, I'll leave the connection content issue open by itself for us to consider/prioritise in the future.
