### ISSUE TITLE
EPIC: OpenSearch: new content 

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#555]
## What should we add to our content collections?
We already have good content from OpenSearch in NodeJS. Use the same subject to bring some python examples in tutorial format. So we can start to have collections for different languages. Reuse the same kaggle data set would be recommended.

Here are some ideas:

- [x] Write search queries with Python in OpenSearch | https://github.com/aiven/devportal/pull/604
- [x] OpenSearch: Get data mapping with Python | https://github.com/aiven/devportal/issues/587
- [x] OpenSearch and logs integration (https://github.com/aiven/devportal/pull/623)

## Is this something you would work on yourself?

[x] I plan to open a pull request for this

**Comment by laysauchoa** [comment]
I have added `OpenSearch: Get data mapping with Python` for the `sample-dataset` tutorial for now. I will use to make reference to `OpenSearch: write search queries`.
