### ISSUE TITLE
[EPIC] Terraform cookbook and recipes

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#559]
We have some useful examples on Aiven Terraform Provider [here](https://registry.terraform.io/providers/aiven/aiven/latest/docs/guides/examples) but these are just the raw Terraform files. To improve on these, the plan is to create some new examples on the DevPortal for our audience to learn how to use Terraform to create Aiven resources. This will take the form of a **cookbook** where each **recipe** shows how to create or configure a couple of Aiven services or integrations with Terraform. In diataxis terms, these content types are reference rather than a howto with numbered steps.

## Ingredients

* Short explanation of what the setup will be and what sort of thing it's useful for
* Diagram of the pieces and how they relate (see `README` for mermaidjs example)
* The terraform files, with explanation of what each part adds, and links to any related materials, such as reference documentation or the product sections. The extra words and explanation give a lot of value to users, so the goal of this type of content is to include explanation and context as well as posting the code samples. 

## Planned recipes

Edit this list and add your own when you're creating something!

- [x] [Standalone Kafka cluster within a single cloud and region](https://github.com/aiven/devportal/issues/863)
- [x] [Kafka with Kafka Connect services with custom configurations](https://github.com/aiven/devportal/issues/864)
- [x] [Standalone PostgreSQL service within a single cloud and region](https://github.com/aiven/devportal/issues/865)
- [x] PostgreSQL services to multiple clouds and regions
- [x] Kafka and OpenSearch with a Kafka Connect OpenSearch Sink connector
- [x] [Kafka and OpenSearch with a Kafka Connect MongoDB Source connector](https://github.com/aiven/devportal/issues/871)
- [x] [M3 and M3 Aggregator services](https://github.com/aiven/devportal/issues/872)
- [x] [Grafana service](https://github.com/aiven/devportal/issues/873)
- [x] [Apache Kafka and Apache Flink Integration](https://github.com/aiven/devportal/issues/883)
- [x] [Terraform Recipe Request - Kafka and Mirrormaker](https://github.com/aiven/devportal/issues/885)

**Comment by lornajane** [comment]
I really like these examples, what a great list! I wonder though if they are really "howto" articles, or if we should break out of the format a little bit and create more of a "cookbook" style. I think the declarative format is less like numbered steps and more like some ingredients ... what do you think?

**Comment by dewan-ahmed** [comment]
> I really like these examples, what a great list! I wonder though if they are really "howto" articles, or if we should break out of the format a little bit and create more of a "cookbook" style. I think the declarative format is less like numbered steps and more like some ingredients ... what do you think?

Yea definitely can be created as a cookbook. I'd like to learn more on what constitutes a cookbook and let's discuss during our upcoming call.

**Comment by lornajane** [comment]
Summarising our meeting discussion: The cookbook can be a new section, I think of it as a special references section. Within it, each page will be a reference-style article (so not a howto with numbered consecutive steps) showing how to do one terraform configuration, with a clear explanation of the components used (maybe a mermaidjs diagram for each one), how they are connected, and ideally what sort of problem this setup would solve.

Then let's paste the Terraform files in full, with explanation of the various configurations and purposes of each section. If we have several Kafka services in different examples, let's configure them differently, one in a VPC, one on a different cloud, one with auto-create topics enabled ... you get the idea. The multiple examples make it more likely that a developer can find what they are looking for.

Adding words and using some of the really good examples we already have in the terraform repo itself, I think will prove very valuable for users.

**Comment by dewan-ahmed** [comment]
All initial tasks completed.
