### ISSUE TITLE
[EPIC] DevOps-related articles migration - help.aiven.io > developer.aiven.io

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#711]
- [x] [Aiven Terraform integration](https://help.aiven.io/en/articles/2370350-aiven-terraform-integration)
- [ ] [Sending service logs to Google Cloud Logging](https://help.aiven.io/en/articles/4209837-sending-service-logs-to-google-cloud-logging)
- [ ] [Using Billing groups via CLI](https://help.aiven.io/en/articles/4720981-using-billing-groups-via-cli)
- [ ] [Getting Started with New Relic](https://help.aiven.io/en/articles/4410033-getting-started-with-new-relic)
- [x] [Terraform to apply "promote to master" on PostgreSQL/MySQL replica](https://help.aiven.io/en/articles/5372422-terraform-to-apply-promote-to-master-on-postgresql-mysql-replica) HowTo
- [ ] [Getting Started -- Kubernetes Logging with Aiven](https://help.aiven.io/en/articles/5271507-getting-started-kubernetes-logging-with-aiven) Repurpose to fit docs.aiven.io as a HowTo and request Dave Beech for a review
- [ ] [Extended Log Retention in Google Cloud Logging](https://help.aiven.io/en/articles/4410105-extended-log-retention-in-google-cloud-logging)
- [x] [Creating a PostgreSQL/MySQL read replica with Aiven Terraform provider](https://github.com/aiven/devportal/issues/1035) cookbook entry

**Comment by dewan-ahmed** [comment]
https://github.com/aiven/devportal/pull/1362 used to resolve **Terraform to apply "promote to master" on PostgreSQL/MySQL replica** task.

**Comment by lornajane** [comment]
@dewan-ahmed this is assigned to you so I won't close it, but since we are done with the migration phase, I would like us to clean up these issues since they no longer need to be open.

**Comment by dewan-ahmed** [comment]
Since we're done with the migration process, I'm closing this issue.
(I worked on the articles based on priority and some of these ones didn't make the cut).
