### ISSUE TITLE
Datadog integration: fixes

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#997]
- [x] Fix the links between articles #998 
- [x] Link Aiven help io pages to the datadog integration page #999 
- [x] Ensure redirection from the help aiven is done #1000
